### ISSUE TITLE
Check in files to Zenodo

### ISSUE THREAD

**Issue by AndyClifton** [IEA-Wind-Task-32/2020-general-meeting-minutes#6]
Once we have a release on Github, we need to check those files in to Zenodo.

Note dependencies:
- [x] #4: Create Zenodo record
- [x] #3: Get DOI from Zenodo
- [x] #5: Create release from GitHub

**Comment by AndyClifton** [comment]
Done. See https://doi.org/10.5281/zenodo.4292208.
